### ISSUE TITLE
安装完提示  [home] is missed

### ISSUE THREAD

**Issue by looping84** [fex-team/yog2#1]
YOG/DISPATCHER 63604: trying to get default router [home]
YOG/DISPATCHER 63604: router [home] is missed, continue

**Comment by xxapp** [comment]
@looping84 我今天也碰到这个问题，我用的是fis3的核心，看了fis-conf.js才明白，fis3应该这样发布：
``` bash
yog2 release debug
```
总的来说就是发布参数的问题

**Comment by Abelarliya** [comment]
@xxapp 我也遇到这个问题，yog2 release debug也不起作用，有其他解决方法么？

**Comment by hefangshi** [comment]
如果你是 fis2 内核而不是 fis3 内核，请使用 `yog2 release -d debug`
