### ISSUE TITLE
yog2按文档操作无法启动

### ISSUE THREAD

**Issue by dangolol** [fex-team/yog2#100]
/Users/Dango/Documents/workspace/zhuzhu/node_modules/yog2-kernel/plugins/isomorphic/index.js:15
        let deps = [];
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

这一行报错，加上'use strict'才行，是我环境的问题？

**Comment by hefangshi** [comment]
1.0.1版本你试试看
