### ISSUE TITLE
中间件安装 400错误

### ISSUE THREAD

**Issue by choukin** [fex-team/yog2#108]
执行
>yog2 plugin install session

提示
>[ERROR] req https://codeload.github.com/fex-team/yog2-plugin-session/tar.gz/master: server relay status code 400.

请问安装中间件时是在project目录还是项目目录里啊

**Comment by hefangshi** [comment]
请安装 yog2@1.0.1 版本解决，之前 github 的zip下载地址有变更，所以插件失效了。
