### ISSUE TITLE
tpl 内嵌 {% script %} 的问题

### ISSUE THREAD

**Issue by puregardenia** [fex-team/yog2#119]
``page/*.tpl ``好像不支持 {%script%} 内嵌 require()的写法
会报``mod.js:141 Uncaught [ModJS] Cannot find module `easydesign:widget/js/index``的错误
但是``widget/*.tpl``支持
是不是考虑加上这个功能。

```javascript
{% script %}
    var result = require("easydesign:widget/js/index");
    alert(result);
{% endscript %}
```

**Comment by hefangshi** [comment]
配置中没有区分page和widget下的tpl对require的支持有什么不同，可以提供一个能够复现的DEMO么？

**Comment by puregardenia** [comment]
刚看到您的spa Demo，发现原来是可以的...
