### ISSUE TITLE
静态资源打包后如何对引用进行替换？

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2#12]
Fis的做法：
http://fis.baidu.com/docs/beginning/getting-started.html#combine
yog2该如何做？
可否以spa demo（https://github.com/fex-team/yog2-spa-demo）举例
谢谢！

**Comment by hefangshi** [comment]
不需要使用任何插件，你只需要按照FIS的文档进行打包配置即可 http://fis.baidu.com/docs/api/fis-conf.html#pack

使用时需要注意的是，FIS的打包不支持一个文件在多个资源包中，也就是无法重复打包。

**Comment by hefangshi** [comment]
另外文档里面有写呀 https://github.com/fex-team/yog2/wiki/%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96#%E6%89%93%E5%8C%85%E5%90%88%E5%B9%B6

**Comment by rendongsc** [comment]
我粗心了，已测试OK，谢谢！

**Comment by rendongsc** [comment]
我粗心了，已测试OK，谢谢！
