### ISSUE TITLE
https session丢失

### ISSUE THREAD

**Issue by superlbr** [fex-team/yog2#121]
求教，设置哪里要变？

**Comment by hefangshi** [comment]
信息太少

**Comment by superlbr** [comment]
1. 首先yog2是依赖express-session或者cookie-session，提供session的支持。问题就变成了express-session或者cookie-session通过https代理需要怎么配置。

**Comment by hefangshi** [comment]
这里面和https代理有什么关系？

**Comment by superlbr** [comment]
我无法判断有误关系，没操作过。 但是我昨天查过了，经过阿里云cdn加速后，session就丢了，目前在工单里撕

**Comment by superlbr** [comment]
有一点就是https-https-http,session会不会掉

**Comment by superlbr** [comment]
我突然想起来了，不是session掉了，而是cdn配置动态请求的时候要设置过期时间为0
