### ISSUE TITLE
前后端分离，Ajax跨域问题如何解决？？？

### ISSUE THREAD

**Issue by Jerry-goodboy** [fex-team/yog2#122]
**我们团队现在遇到一个小问题，就是 Ajax跨域的问题，我们的开发场景 是这个样子滴：**
* 我们只负责前端交互逻辑，数据CURD全部由接口负责，但是涉及到跨域；
* 其次我们开发的前端代码暂时还无法部署到他们的WEB服务器上，若能布置上，应该不涉及跨域问题；
* 最关键的是，CORS服务器端的跨域和JSONP跨域，接口全部不支持；

**我们目前的解决方案：**
- 使用PHP做了一层后台代理，我们前端的代码放到了PHP的Apache服务器上，真实的数据接口全部用PHP重新封装了一遍。

请问大神们，对于这种开发情景，Ajax跨域开发的最佳实践是什么？
@nwind @miller @tianlili @hefangshi

**Comment by hefangshi** [comment]
确定这个问题和YOG2有关系？

**Comment by Jerry-goodboy** [comment]
因为 不太了解，所以想问一下，如果用YOG2来写程序，涉及到的跨域问题，如何解决？@hefangshi

**Comment by hefangshi** [comment]
YOG2作为UI层，原则上是希望所有ajax请求都经过Node.js的，所以不存在这个问题。如果碰到这种问题会采用透明代理解决。

**Comment by Jerry-goodboy** [comment]
@hefangshi 这些 YOG2都做好了是吗？我刚刚从一个大神那里了解到nginx转发来跨域调用接口的方法，咱们YOG2也有类似的功能是吗？

**Comment by hefangshi** [comment]
你的需求应该不需要使用YOG2

**Comment by Jerry-goodboy** [comment]
@hefangshi 那我应该用什么，大神赐教，现在前端模板，MV**框架，后端模板，都把我绕蒙了，我们现在就是做前端，就像 APP的那种，但是WEB涉及到跨域，这种开发场景应该如果技术选型，求指导

**Comment by hefangshi** [comment]
看你在FIS3下已经开了一个讨论了，就不用重复讨论了，nginx,fiddler,charles都是选择。

**Comment by dodio** [comment]
@Jerry-goodboy  如果你说的前端指的是浏览器前端，你更多应该使用的是mock。
