### ISSUE TITLE
scss的编译问题

### ISSUE THREAD

**Issue by submerge** [fex-team/yog2#124]
下载官方的demo运行。
在----widget
        |-------message
             |--------message.tpl
             |--------message.scss
执行yog2 release debug message.scss并不会被编译成message.css.
改成message.less,在编译，message.less就会编译成message.css。
这个应该是有一个默认的fis-config配置文件吧？如果有，在什么地方能看到？

**Comment by hefangshi** [comment]
什么demo有sass？yog2默认没有集成sass啊。

**Comment by submerge** [comment]
@hefangshi 执行这个命令# _yog2 init app_之后的demo,message.scss是我加的。
我想问的是message.scss默认不会被编译，message.less就可以被编译。
应该是有一个默认的fis-config.js配置文件？如果有会在什么地方呢？

**Comment by submerge** [comment]
@hefangshi  好像是找到了。在执行yog2 release命令时，有个yog2.js的文件会被执行。默认的fis-config配置文件是这个吧？

**Comment by hefangshi** [comment]
是的

**Comment by submerge** [comment]
@hefangshi 提一个小建议，可以把这个加到文档里

**Comment by hefangshi** [comment]
参考FIS3文档即可。解决方案当然不可能把FIS所有插件的功能都合并在一起。
