### ISSUE TITLE
node-ral的配置文件目录

### ISSUE THREAD

**Issue by submerge** [fex-team/yog2#125]
请问在app项目中，node-ral的配置文件应该放置到哪个目录下？
app目录结构如下
&ensp;|---client
&ensp;|---server
&ensp;|---config
&ensp;&ensp;|---ral
执行yog2 release 之后，结果config/ral/API.js被发布到了/statci/home/config/ral目录下了。
正确的应该是发布到project项目的/conf/ral/目录下吧？

**Comment by submerge** [comment]
我自己加了行配置
fis.match('/config/(**.js)', {
    release:'/conf/$1'
});
默认的配置文件里好像没有处理app项目的config目录。。。

**Comment by 303182519** [comment]
这样试一下

fis.match('/config/ral/(**.js)', {
    release:'../conf/ral/$1'
},true);

**Comment by huqiliang** [comment]
这个应该属于整个项目配置吧，不在app里面增加 在yog/conf/ral里面新增

**Comment by hefangshi** [comment]
默认并没有把配置从app发布至基础环境目录，你需要在基础环境而非APP代码中添加。
