### ISSUE TITLE
静态资源发布

### ISSUE THREAD

**Issue by submerge** [fex-team/yog2#126]
yog2的项目。静态资源的访问地址是host/static/js/test.js(host是主机名比如www.baidu.com)
想把静态资源的访问地址改为host/cms/static/js/test.js应该怎么操作啊？
求大神指点

**Comment by hefangshi** [comment]
可以了解FIS的domain配置，最简单的来说就是

fis.match('/client/**.js', {
    domain: 'https://www.baidu.com'
});
