### ISSUE TITLE
关于对async/await的支持

### ISSUE THREAD

**Issue by huqiliang** [fex-team/yog2#127]
请问目前yog2对async/await支持吗 发现前面有两个issue是写着支持的 想问下具体应该怎么写？
我直接写 await 后面跟 Promise 报语法错误

**Comment by hefangshi** [comment]
后缀名需要改为*.es

或者主动添加配置启动js后缀的支持

另外需要运行时的Node.js版本支持generator，版本大概要求是0.12或4以上。

```javascript
fis.match('/server/**.js', {
    parser: fis.plugin('typescript', {
        module: 1,
        target: 2
    })
});
```

**Comment by huqiliang** [comment]
万分感谢

**Comment by huqiliang** [comment]
还是报错：SyntaxError: Unexpected strict mode reserved word

1.fis配置也改了

2.后缀名改为.es 

已经确认对其他es6语法是支持的

node版本：4.5.0
yog版本：1.4.0

**Comment by hefangshi** [comment]
应该是你的代码语法问题，比如出现这个最典型的一个问题就是

await必须写在async函数中。
