### ISSUE TITLE
部署到线上用什么作为文件接收器和重加载呢？

### ISSUE THREAD

**Issue by morer** [fex-team/yog2#133]
看到这个
`recv-reload plugin is running in /yog/upload, please disable it in production` 表示不知道发布到生产环境的时候，有没有可以用的代替方案来作为文件接收器和重加载，难道要用fis3的那套接收器后台？如果这样，fis3的配置岂不是要改比较多。求指导。

**Comment by hefangshi** [comment]
线上是使用文件覆盖的方式部署的，并非使用fis3或者yog2的发布功能，因为这样的发布功能留在线上是十分危险的。举例来说你可以这样做

```bash
yog2 release prod -d output
cp output/* {PATH/TO/YOG2}
cd {PATH/TO/YOG2}
pm2 restart
```

**Comment by morer** [comment]
明白了， 谢谢
