### ISSUE TITLE
fis3 命令，配置部分资源不使用hash和合并打包等功能，不起作用

### ISSUE THREAD

**Issue by jnlong** [fex-team/yog2#141]
配置如下：
fis.match('/static/img/news/**.{png,jpg,gif}', {
    useHash: false
});
fis.match('/widget/**.{js,es6}', {
    packTo: 'widget.js'
});
fis.match('/widget/**.{css,less}', {
    packTo: 'widget.css'
});

**Comment by hefangshi** [comment]
可以用yog2 inspect --files path/of/file --fis3 调试一下原因

**Comment by jnlong** [comment]
执行 yog2 inspect --files path/of/file --fis3
提示 Error: undefined property [namespace].

**Comment by jnlong** [comment]
谢谢hefanshi 的热心帮助。
通过 yog2 inspect debug-prod --fis3, 查看日志，找到原因；路径前需要添加 /client,配置如下
fis.match('/client/static/img/news/**.{png,jpg,gif}', {
    useHash: false
});
fis.match('/client/widget/**.{js,es6}', {
    packTo: 'widget.js'
});
fis.match('/client/widget/**.{css,less}', {
    packTo: 'widget.css'
});
