### ISSUE TITLE
测试联调有没有好的解决方案？

### ISSUE THREAD

**Issue by DeyuanTan** [fex-team/yog2#156]
怎么根据环境的不同加载不同的配置。比如：
测试环境下自动加载 /path/a.test.js
 生产环境加载 /path/a.js

**Comment by hefangshi** [comment]
http://fex.baidu.com/yog2/docs/plugin-system/#插件配置

自带环境变量切换线上线下环境

**Comment by DeyuanTan** [comment]
这个是插件那一块的吧？我这边是在client目录下，基本每个client都有一个配置文件，场景不怎么一样
