### ISSUE TITLE
project 可以断点调试么 下面是我的vscode配置

### ISSUE THREAD

**Issue by hans007** [fex-team/yog2#157]
`
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "启动程序",
            "program": "${workspaceRoot}/app.js"
        },
        {
            "type": "node",
            "request": "attach",
            "name": "附加到进程",
            "address": "localhost",
            "port": 5858
        }
    ]
}
`

无法进入自己的js代码断点调试

**Comment by hefangshi** [comment]
和普通的node.js程序的调试是完全一样的

**Comment by hans007** [comment]
谢谢回复 我已经解决了
还是 vscode的环境配置问题，在WebStrom下完美兼容
