### ISSUE TITLE
关于图片资源内嵌的问题

### ISSUE THREAD

**Issue by naoxiaozhi** [fex-team/yog2#167]
根据官网的说明 在html中嵌入图片base64 可以写成如下形式
 ` <img title="百度logo" src="images/logo.gif?__inline"/>`

在我的项目中，我写成如下形式：
`<img src="/static/wap/static/common/img/logo.png?__inline"/>`

在release的时候，报错：
**[ERROR] unable to embed non-existent file ["/static/wap/static/common/img/logo.png?__inline"] in [/client/widget/common/header.tpl]**

我想问一下，使用这种方式内嵌的时候有什么特定的条件吗？

**Comment by hefangshi** [comment]
按照源代码路径而非发布路径编写

**Comment by naoxiaozhi** [comment]
果然是因为这个 3Q~
