### ISSUE TITLE
在中间件配置是不是不适合做 单例的全局对象初始化？

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2#17]
前一个问题：https://github.com/fex-team/yog2/issues/16
如果在此添加自定义中间件，那么每一个requst都会进入此中间件的方法。
有何建议？

**Comment by hefangshi** [comment]
恩，我说错了，这类需求可以用用户插件解决

https://github.com/fex-team/yog2/wiki/%E6%8F%92%E4%BB%B6%E7%B3%BB%E7%BB%9F#%E7%94%A8%E6%88%B7%E6%8F%92%E4%BB%B6

**Comment by hefangshi** [comment]
另外这里有一份mongoose的加载中间件，可以直接使用。

不过应该没对热加载特殊处理 https://github.com/will-/yog-plugin-mongoose

**Comment by rendongsc** [comment]
已测试通过，明白了yog全局服务对象的加载机制！
希望后面的同学注意！
