### ISSUE TITLE
自定义插件如何在Node服务器停止前做些清理工作？

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2#18]
通过自定义插件创建了些全局服务对象，比如数据库连接等，在Node服务器停止前如何调用相关的清理代码，如：关闭数据库连接等！
yog2-kernel好像没有直接对应的事件？

**Comment by hefangshi** [comment]
一般来说并不需要这类工作。。。

**Comment by rendongsc** [comment]
有这方面的需求，比如在自定义插件初始化阶段 new MongoClient且connect()，之后作为全局服务对象，在Action通过require('yog2-kernel').app来调用全局的MongoClient，业务代码始终不close db。那么如果在node 服务停止时 调用全局服务对象的close方法？
难道需要每次数据库操作都去connect，做完立即close？

**Comment by hefangshi** [comment]
不需要close，一直保持开启状态，如果断开了就继续重连。

服务停止的时候，实际上就已经是自动断开了。

**Comment by rendongsc** [comment]
在yog2-kernel增加shutdown事件，这样可以做些全局的清理工作。

**Comment by hefangshi** [comment]
这样的事件，即使添加了也并不可靠。而不做清理工作，也不会带来什么问题。
