### ISSUE TITLE
编译less框架源码报错.

### ISSUE THREAD

**Issue by eugeneCN** [fex-team/yog2#180]
![image](https://user-images.githubusercontent.com/21122802/31398958-46424464-adb0-11e7-9653-500f8b3443e7.png)

引入了阿里的sui移动端框架无法编译less，报错变量未定义。

报错信息：[ERROR] parser.less: variable @border-default-color is undefined

但是在纯fis3项目里是可以滴，如何解决? @hefangshi

**Comment by zhiqiang21** [comment]
这种报错都会有出错的行数吧，找到出错的文件，全局搜下这个变量名看看在使用的是否声明了

**Comment by eugeneCN** [comment]
不适用yog2可以编。

**Comment by zhiqiang21** [comment]
yog2默认也是使用fis进行编译的。是不是缺少插件parser

**Comment by eugeneCN** [comment]
您是fex团队的成员吗，麻烦帮忙看下我的[issue](https://github.com/fex-team/yog2/issues/184)。
