### ISSUE TITLE
Yog2 支持独立子项目，但是配置是统一管理的？

### ISSUE THREAD

**Issue by 599316527** [fex-team/yog2#182]
有个疑惑，看文档感觉只有 yog/conf 目录是放配置的，每个 Project 里只有 server 和 client，是否意味着配置是统一下 yog 下管理的？

如果存在对于不同的 Project 有不同的配置的情况该如何处理？

比如，node-ral 对于不同 Project 对接不同的后端服务，混在一起管理是否不太合理？

**Comment by zhiqiang21** [comment]
按照yog的设计思想 app是放置  server和client的。project是管理app的，所以在project下会有项目的配置文件。

一个project可以包含多个app，多个app是可以相互独立的。分别独立的app又可以公用相同的后端服务配置。如果有不同的后端服务需要访问，`conf/ral/xxxxservice.js`中对于不同的服务分别命名不同的别名即可，在app中调用ral的使用，通过yog.ral('xxxx别名'，)就可以了

**Comment by 599316527** [comment]
所以就是没法分 app 放 conf 咯？

**Comment by zhiqiang21** [comment]
当然是可以的，看你是什么配置文件。`ral`变量在yog里面是一个全局变量。
如果你是用的ral服务，在`conf/plugins/ral.js`文件中有这样一段`confDir: yog.ROOT_PATH + '/conf/ral',`就是加载ral的配置文件的。你再app中单独配置的话，就需要写加载你app的ral配置的语句。但是应该不建议这么做。我认为上面说的配置别名应该能满足你的需求。

如果你不是使用的`ral`比如说是数据库的配置，那就在app的server目录下随便建个conf的目录放数据库的配置就好了。
