### ISSUE TITLE
启动pm2进程管理器   yog2 release 无法push文件

### ISSUE THREAD

**Issue by wufangjian** [fex-team/yog2#186]
1、启动pm2进程管理器
2、yog2 release 发布代码

控制台报错：
```
node_modules/fis3-deploy-http-push/index.js:228
            throw new Error(error.errmsg || error)
            ^
```

**Comment by Yidada** [comment]
你是不是直接pm2 start app.js

**Comment by wufangjian** [comment]
@Yidada 是的

**Comment by Yidada** [comment]
pm2 直接start app.js 相当于production环境，是不加载那些接受代码的yog功能的，所以你可以弄个脚本里面放yog2 run然后用pm2启动，或者参考package.json里面debug的scripts方式用pm2启动。
