### ISSUE TITLE
如何配合ORM比较好？如Sequelize，而且多个App呢

### ISSUE THREAD

**Issue by superlbr** [fex-team/yog2#19]
rt

**Comment by hefangshi** [comment]
多个 App 的话，可以在每个 App 的 `router.js` 中去做一些初始化工作，这样每个 App 都可以有独立的 ORM 逻辑。

实际上每个 App 的 `router.js` 就是传统 express 应用的 `app.js`，希望这样解释你就可以豁然开朗了。
