### ISSUE TITLE
如何在Action中获取全局的app或router对象？

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2#20]
aciton：
module.exports = function (req, res) {
    res.render('spa/page/contact.tpl', data);
};
通过plugin注册了些单例对象，如果在action访问app或router对象？

**Comment by hefangshi** [comment]
plugin的单例对象建议直接挂在 yog 对象上，这是一个全局对象。

不太建议在action中访问你说的这两个对象，不过的确是可以的。

```
yog.app
```

```
yog.dispatcher.router('home').action('index')
```

**Comment by rendongsc** [comment]
不建议的详细原因？
全局插件的创建依赖于配置，如果在每一个app都重复配置或者创建，那么代码冗余，而且消耗了更多的资源。
有何高见？

**Comment by hefangshi** [comment]
我并非说不建议对一些基础功能挂载全局变量。我是指不建议在 app 中访问 app 与 router 对象。

插件本身就是为了全局初始化而准备的功能，插件在整个 project 运行过程中只会执行一次，并不是要每个 app 都重复执行的。

**Comment by rendongsc** [comment]
建议把此类问题体现在新的demo代码中。
谢谢耐心解释！
