### ISSUE TITLE
app的实时发布不能检测文件删除。。。

### ISSUE THREAD

**Issue by superlbr** [fex-team/yog2#21]
rt

**Comment by superlbr** [comment]
还有model能不能自动根据数据库生成呀。。。

**Comment by hefangshi** [comment]
FIS的发布都是增量的，也就是说你即使删除了文件，也不会在服务端删除。

另外model这种问题，yog2 并没有提供任何数据库支持，所以即使要支持，也是 orm 库去支持，我倒是用过一个 orm 库叫 waterline，他可以自动根据 model 生成数据库，而非根据数据库自动生成 model。

**Comment by superlbr** [comment]
waterline有滴，stormslowly/ms2sm.不过waterline对mysql支持不够好。

yog2能不能帮忙理理图片呀，整理，重命名，定位啥的

**Comment by superlbr** [comment]
App 里router.js的更新也没有自动发布过去。。。

**Comment by hefangshi** [comment]
`router.js` 是肯定会自动发布过去并且生效的。你再排查看看。

> yog2能不能帮忙理理图片呀，整理，重命名，定位啥的

不知道你说的是不是 fis 的功能，fis 有的，yog2 里面都有。

**Comment by superlbr** [comment]
![image](https://cloud.githubusercontent.com/assets/8142164/8561758/9b07df1a-255c-11e5-91c4-f7401ace3cf8.png)
哥们，你们跟frozen.js干上了

**Comment by hefangshi** [comment]
模块化方案有冲突呗，既然有冲突，就直接以非模块化的方式去加载吧。记得在 mod.js 之前去加载它。

**Comment by superlbr** [comment]
求教，pm2该如何发布yog2呀

**Comment by hefangshi** [comment]
入口定为app.js就可以了，没有特别需要注意的地方，可以直接使用pm2的fork模式

**Comment by superlbr** [comment]
pm2 start app.js,那env参数呢

**Comment by hefangshi** [comment]
参考 pm2 的文档
