### ISSUE TITLE
static/js 文件没有输出？

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2#28]
模板layout.tpl已包含：jquery-2.1.1.min.js等文件，运行后在chrome下查看<head>并没有js文件输出，怎么回事呢？
模板如下：
<!doctype html>
{% html lang="en" framework="home:static/js/mod.js" %}
    {% head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/static/favicon.ico">
        <title>{{ title }}</title>
        {% require "home:static/css/app.css" %}
        {% require "home:static/js/jquery-2.1.1.min.js" %}
        {% require "home:static/js/bootstrap.min.js" %}
    {% endhead %}
     {% block content %}
     {% endblock %}
    {% require "home:page/layout.tpl" %}
{% endhtml %}

**Comment by xiangshouding** [comment]
你缺少了

```
{%body%}
{%endbody%}
```

**Comment by rendongsc** [comment]
写在继承的页面了，因为要对body多些特殊设置。
{% extends 'home:page/layout.tpl' %}

{% block content %}
<body class="login">
<section id="content">
。。。

**Comment by rendongsc** [comment]
body写在继承的页面了！

**Comment by rendongsc** [comment]
加了：
{%body%}
{%endbody%}
就OK了，谢谢！
