### ISSUE TITLE
Swig模板引擎与Vuejs如何 和谐？

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2#30]
Swig模板引擎与Vuejs 都是用{{ 来做tag，服务端渲染后把本该属于前端的html标记全部置为空了。

**Comment by rendongsc** [comment]
自解，可以通过设置Vuejs的分隔符：
Vue.config.delimiters = ['(%', '%)']
解决冲突！

**Comment by superlbr** [comment]
@rendongsc 怎么整合的呀

**Comment by dodio** [comment]
服务端 swig 可以使用 {%raw%}标签
