### ISSUE TITLE
前端js如何 require 非widget目录下的Js模块？

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2#31]
如果js文件在widget目录下，是OK的！
如果放在其他目录下，比如与page的同一目录下则会报错： 
Uncaught [ModJS] Cannot find module `home:page/other.js`

**Comment by xiangshouding** [comment]
只有 widget 目录下的资源才会进行组件化封装只有组件化封装了的资源才能在 js 中用 `require(id)` 来调用执行。

**Comment by rendongsc** [comment]
fi3，加：isMod: true,可以不？
//components下面的所有js资源都是组件化资源
fis.match("components/**", {
    isMod: true,
    release: '/static/$0'
});

**Comment by hefangshi** [comment]
可以是可以，但是不建议加太多的目录规范，增大学习成本

希望模块化的就放到widget下面就好了

**Comment by eugeneCN** [comment]
fis.match is not a function

![image](https://user-images.githubusercontent.com/21122802/31326372-35efb60c-ac8c-11e7-91d8-c2a6310a501c.png)

**Comment by eugeneCN** [comment]
![image](https://user-images.githubusercontent.com/21122802/31326401-76fffe68-ac8c-11e7-9818-3d9d9008b3c4.png)
我是这么理解，widget是用来放组件的，其他的一律不要，我需要一些公共方法，我只想在目录里多一层，utils告诉我怎么做。 @hefangshi

**Comment by eugeneCN** [comment]
知道了，原来用的yog2默认用fis2编译的 ... so ... yog2 release debug --fis3
