### ISSUE TITLE
怎么在别的目录使用短名调用其他目录的组件啊

### ISSUE THREAD

**Issue by huqiliang** [fex-team/yog2#32]
比如我在home的某个js中这样写 var $ = require('common:components/jquery/jquery.js');可不可以直接var $ =require('jquery') 在当前app是可以的 跨app应该怎样配置？

**Comment by hefangshi** [comment]
不能跨app用短名，fis-components是模块级别的，跨模块引用必须使用全称

**Comment by Luoxinfang** [comment]
你可以使用yog.require('common:components/jquery/jquery.js')
