### ISSUE TITLE
微信授权目录设置无效

### ISSUE THREAD

**Issue by superlbr** [fex-team/yog2#34]
1）问题描述：微信端支付调用时报错
2）错误提示：getBrandWCPayRequest:fail_no permission to execute
3）更多信息：
    付款链接  http://omega.mktou.com/mktou/m_success?orderNo=15082159006 (可测试)
    调用支付路由  /pay/wechatpayJsapi
    调试窗口输出 
    ![1](https://cloud.githubusercontent.com/assets/8142164/9622436/92ba8c10-5165-11e5-94d0-5e722d839ae3.jpg)

    怀疑dispatcher导致调用路径不一致，但是不清楚原因。    

    报错截图
 
 ![image](https://cloud.githubusercontent.com/assets/8142164/9621885/0ae63af6-515f-11e5-92c1-098ed09b8535.png)
   
   支付授权目录已配置
    ![image](https://cloud.githubusercontent.com/assets/8142164/9621898/345f9030-515f-11e5-9c5b-fae653418083.png)

   oauth目录已配置
   ![image](https://cloud.githubusercontent.com/assets/8142164/9621904/441df0ac-515f-11e5-8d40-1114684ad675.png)

  js，安全域名已配置
  ![image](https://cloud.githubusercontent.com/assets/8142164/9621908/52c49548-515f-11e5-8ed7-041ece01761c.png)

**Comment by hefangshi** [comment]
应该和dispatcher无关，我并未使用过微信授权目录设置，但是我看了一眼文档，似乎是要求提供一个二级目录或者三级目录，这里的关键词是目录，而你的 /pay/wechatpayJsapi 是一个URI路由，你可以尝试看看在action的/pay/wechatpayJsapi下再建立一个action文件，让这个请求是在目录下而非目录本身。

**Comment by superlbr** [comment]
如是如是

**Comment by hefangshi** [comment]
解决了？

**Comment by superlbr** [comment]
是的，就是目录不对，往上设到 /pay/就好了

**Comment by hefangshi** [comment]
ok
