### ISSUE TITLE
xml如何处理比较好

### ISSUE THREAD

**Issue by superlbr** [fex-team/yog2#35]
就是这种req.body.xml？

**Comment by hefangshi** [comment]
目前没有找到特别好的xml库，xmlreader可以一用，不过之前版本似乎有些bug，而且功能支持的不全，你可以试试看。

**Comment by superlbr** [comment]
node-ral不可以么

**Comment by hefangshi** [comment]
当初调研过node的xml解析库，没有很成熟的，因此没添加支持，你可以设置unpack为string，然后自行用xml库进行解析。

**Comment by superlbr** [comment]
加个future吧

**Comment by hefangshi** [comment]
xml是一个很复杂的格式，而且需求不同，对xml转换的期望也不同，有的是希望完整包括各种ns和attr的转换，有的是希望直接舍弃大部分内容转为JSON格式，众口难调，而且xml目前用的也不多，所以暂时不会有支持。

**Comment by superlbr** [comment]
自己结案:参考http://stackoverflow.com/questions/11002046/extracting-post-data-with-express，https://github.com/balderdashy/sails/issues/2714。connect/lib/utils可以用express-utils替换，不要也行用req.headers['content-type']。

**Comment by superlbr** [comment]
有没有yog2 的react\ng插件

**Comment by superlbr** [comment]
node-ral作为plugin可以删除么

**Comment by hefangshi** [comment]
@superlbr 可以，从http.js里面去掉就可以了，还可以直接在ral.js的配置里面添加YOG_DISABLE: true
