### ISSUE TITLE
如何在yog2(中间层)层得到后端响应(response Headers),而不只是数据?

### ISSUE THREAD

**Issue by ZuoweiWang** [fex-team/yog2#36]

**Comment by hefangshi** [comment]
你应该是指的node-ral无法获得后端响应的头信息吧？

由于设计之初的理念是node-ral是一个数据交互的类库而非特指HTTP的，而是包括socket等请求协议的后端资源管理库，因此没有为HTTP协议特别打造一个获取headers的接口。

但是从现在的使用情况来看，这样的限制有些太死了，有时候获取headers处理一些问题会更加便利一些。

所以结论就是目前ral'是无法获得响应的头信息的，但是未来会加上。

**Comment by ZuoweiWang** [comment]
首先,谢谢作者提供这么好的包包~~~~

我膜拜了一下你的代码,只好在node-ral包里的ext/protocol/httpProtocol.js里做一下文章了~~,

我是这样改的,有点撮^_^
function ResponseStream() {
    this.writable = true;
    this.data = null;
    this.chunks = [];
    //2015/9/6--res.headers@dimitri
    this.extHeaders = null;
}
''''''''''''''''''''''
 var req = request.request(opt, function (res) {
        //2015/9/6--res.headers@dimitri
        response.extHeaders = res.headers;
'''''''''''''''''''''''''''
this.emit('data',[data, this.extHeaders]);
this.emit('end');
"""""""""""""""""

作者有什么好方法吗?

**Comment by hefangshi** [comment]
this.emit('data',[data, this.extHeaders]);
会调整成 this.emit('data',data, this.extHeaders);

但是光这样还不够，因为实际上请求协议里返回的数据，还会在ral核心中经过数据解包才会返回用户，因此还需要调整一下https://github.com/fex-team/node-ral/blob/master/lib/ral.js#L137-L156 这部分，让他能支持更多的参数返回。

**Comment by ZuoweiWang** [comment]
嗯嗯~

**Comment by ZuoweiWang** [comment]
经过作者提示后,我改了一下(我是偏做页面的前端,改的不太好,期待作者下一个版本)
if(conf.unpack=='raw') {
                        unpack = context.unpack(conf, data);
                    }else{
                        unpack = context.unpack(conf, data[0]);
                        unpack =[unpack, data[1]];
                    }

**Comment by superlbr** [comment]
吾观fis4跃跃欲试，yog3已不久矣

**Comment by hefangshi** [comment]
fis4?你是说fis3么？现在yog2已经支持fis3了，安装最新版，yog2 release debug --fis3就可以使用fis3内核编译了。具体可以参考文档。

**Comment by superlbr** [comment]
no! no! no! 我说的是fis3的下一代版本fis4，八卦一下，swig已经没人维护了，react/ng的特性很让人眼馋

**Comment by ZuoweiWang** [comment]
e,e,e~~..好吧,fis3 也眼馋reactjs,发布了一系列插件~~~
fis-parser-jsx-react@1.0.0
fis-parser-babel-react@1.0.0
( es6 的语法is my love)
不过最重用的还是框架设计思想~~,这是我想要学习的~~

**Comment by hefangshi** [comment]
react/ng与yog2并不冲突，只不过react和ng都是重前端渲染，而yog2一部分的长处在于后端渲染，所以联合使用起来会有些感觉使不上力，但是你依然可以把yog2作为前端restful api的提供者，然后使用react/ng来做前端渲染，我们有很多这种类型的项目。

**Comment by ZuoweiWang** [comment]
嗯嗯~

**Comment by hefangshi** [comment]
done https://github.com/fex-team/yog2/issues/40
