### ISSUE TITLE
单独使用yog2-kernel时 ral 插件报错

### ISSUE THREAD

**Issue by dodio** [fex-team/yog2#50]
排查是一个ral在引用内置的log模块的默认配置时少漏了.log
即
module.exports.ral.defaultConf = {
    confDir: yog.ROOT_PATH + '/conf/ral',
    logger: require('../log').defaultConf
};

应为：
module.exports.ral.defaultConf = {
    confDir: yog.ROOT_PATH + '/conf/ral',
    logger: require('../log').log.defaultConf
};

**Comment by hefangshi** [comment]
的确是有问题，感谢反馈
