### ISSUE TITLE
ral提供mock功能

### ISSUE THREAD

**Issue by hefangshi** [fex-team/yog2#52]

**Comment by hefangshi** [comment]
done https://github.com/fex-team/node-ral/commit/ddcdcb78d7101c61aa289d4b67085894cceae1d3

**Comment by dodio** [comment]
mock 怎么配？

**Comment by hefangshi** [comment]
尚未发版

https://github.com/fex-team/node-ral/blob/master/test/ral/mock/mockGET.js
