### ISSUE TITLE
插件形式提供react预渲染能力

### ISSUE THREAD

**Issue by hefangshi** [fex-team/yog2#54]

**Comment by rendongsc** [comment]
很好！
建议：对于新增功能时可否先把文档给更新了，最好给个简单的代码示例。
谢谢！

**Comment by superlbr** [comment]
貌似代码好久没更了

**Comment by hefangshi** [comment]
@rendongsc 功能待开发，这里只是issue

@superlbr yog2的repo只承载了cli和文档的功能，运行时核心代码在https://github.com/fex-team/yog2-kernel

**Comment by v-joy** [comment]
强烈关注    最近正好也在学习react && 组内也有做hybrid的需求&&今后可能使用react/react-native   强烈期待

**Comment by superlbr** [comment]
high-prio

**Comment by superlbr** [comment]
0.4.6开始support jsx渲染咯。。

**Comment by superlbr** [comment]
额，貌似刚刚的提交才解决了这个bug

**Comment by ascoders** [comment]
这是我写的基于yog2 react 同构插件 https://github.com/fit-component/isomorphic-redux-tools
使用方法参考：https://github.com/fex-team/fit/issues/1
编译脚本开源：https://github.com/fit-component/isomorphic-build

**Comment by ascoders** [comment]
理论讲 React 预渲染是与后端框架无关的，作为一个前端插件可能更合适

**Comment by hefangshi** [comment]
https://github.com/fex-team/yog2-kernel/commit/098a81fb4fda37e2e81cbaa1243e9efd030033e8 落地
