### ISSUE TITLE
在plugins/dispachter中shiftUrl 有问题

### ISSUE THREAD

**Issue by dodio** [fex-team/yog2#55]
在66行等地方使用了：
req.url = shiftUrl(req.url)改变了原本的地址
没有在dispatcher 没有匹配到action 时进行恢复。

会导致后续的应用无法正确获取 req.path 
建议在
相应的next()之前加上 req.url = req.originalUrl;

**Comment by hefangshi** [comment]
是故意这样处理的，这样的好处是，在APP的router中，可以单纯的考虑进入APP后的路由情况，这样就可以让一个APP可以在不同的业务场景下使用不同的APP级路由并且对其自身是透明的。

相反，如果你希望在APP中获取真实的访问URL，你应该使用 `req.originalUrl`

**Comment by dodio** [comment]
嗯。了解，我估计也是这样的策略。
只是，dispatcher 中间件之后的就受影响了。
所以我说看能在 next（）调用之前恢复一下。

**Comment by dodio** [comment]
对了，再问一个问题，swig 怎么输出 压缩了的html呢？ 就是去掉了换行的html

**Comment by dodio** [comment]
对了，再问一个问题，swig 怎么去除空格和换行呢？

**Comment by hefangshi** [comment]
你是指FIS的 widget 和 require 之类的tag导致的空格和换行么？目前还不能去除。

**Comment by dodio** [comment]
不是。就是 swig ，像 jade 可以配置是否去掉空行空格等。
swig 我翻文档没看到怎么做。

**Comment by hefangshi** [comment]
没有这样的功能
