### ISSUE TITLE
release app后自动删除yog2下app残余

### ISSUE THREAD

**Issue by superlbr** [fex-team/yog2#56]
如题，增量更新没有意义

**Comment by hefangshi** [comment]
就个人而言，这个功能的意义不大，因为我们的运行时目录中，app这类目录都是直接ignore掉不提交的，所以开发期的残余不会影响正常使用和开发，上线则是统一增量部署，也不会有太大的影响。

反而是在windows下由于系统机制原因，经常会导致文件删除异常这样的使用，也是为了避免这类不必要的麻烦，没有实现这样的功能。
