### ISSUE TITLE
开启但不使用bigpipe模式时未触发end事件

### ISSUE THREAD

**Issue by dodio** [fex-team/yog2#58]
在开启bigpipe模式，但是模板中又没有使用bigpipe模式时。
yog-view conbine.js 中
.on('end', function () {
                stream.push(clouser);
                done();
            });
end 事件并没有触发。
表现为： 最终渲染出的页面 缺少 &lt;/html&gt; 标签

**Comment by hefangshi** [comment]
`开启bigpipe模式`是什么概念？

**Comment by dodio** [comment]
不是，你们的bigpipe 在view （conf/plugins/view.js 34行左右）的配置项里是能配置里 是能配置
bigpipe 是否启动嘛。当设置为true后，
在模板中没有使用 widget 的情况下，最终输出的html 就会少掉 末尾的 &lt;/html&gt;标签。

**Comment by hefangshi** [comment]
首先，bigpipe默认都是开启的，其次我们也有大量页面没有bind，并不会出现少掉末尾的html的情况，你可以提供一个demo么？

**Comment by hefangshi** [comment]
比如我

```
module.exports = function (req, res) {
    res.render('core/page/a.tpl');
}
```

```
<!DOCTYPE html>
{%html%}
<head>
</head>
{%body%}
aaaaa
{%endbody%}
{%endhtml%}
```

这样渲染一个页面，并没有出现你说的这种情况

**Comment by dodio** [comment]
恩。其实我自己是对 yog2-kernel 运行时 有做改造（只是对结构什么的做过一些调整，也是直接用的yog-view,yog-bigpipe,yog-swig等等)，我也测试了yog2 demo ，确实不会少末尾的 html。
我再检查检查是什么问题。

**Comment by dodio** [comment]
https://github.com/dodio/fa-core
我改的，我是放在了这里。

**Comment by dodio** [comment]
对了，我能问您一个问题吗？
fis3 现在有 seajs transport  的插件，或者解决方案吗？至少我在 fis 官网插件列表里没有找到。

**Comment by dodio** [comment]
以及，yog-view 获取渲染后的内容的方式？

**Comment by hefangshi** [comment]
并不推荐使用seajs，当你习惯了前端编译的能力后，实际上大部分seajs的功能并没有实际意义或者说不是最佳实践。

https://github.com/fex-team/fis3-demo/tree/master/use-seajs

**Comment by hefangshi** [comment]
你的 fa-core 看不到基于 kernel 的提交记录，我一时也看不出来。。但是看起来是很有意思的尝试，也许未来yog2也会吸取一些其中的经验。

yog-view相对来说应该是比较独立的一个组件，漏掉html这种事情更是奇怪，期望应该是只要提供了`mapjson`中间件，应该是可以在任何express应用下使用的。

我建议你看看swig的编译缓存吧，可能需要debug到swig模块内部才行。

**Comment by dodio** [comment]
嗯。因为其实我还没习惯，在编译阶段去解决依赖问题。
在开发的时候写@require 标注之类的形式，我自己是还没有习惯。
然后seajs对于我来说不仅解决了依赖和加载的问题，还有相对方便的命名空间。

fa-core 当时我做的时候，忘记从 kernel 的库上去fork了。

**Comment by dodio** [comment]
话说，真的是很感谢 fis 和 yog。

**Comment by dodio** [comment]
关于那个，缺少末尾 html 的问题。其实 end 我第一楼提到的那几行代码，是执行到了.
变量 clouser 中的内容也是 &lt;/html&gt; 但是 stream.push(clouser) 了以后，看起来像没生效一样。输出里面，没有  &lt;/html&gt;

**Comment by hefangshi** [comment]
你可以通过res.end和stream.push这两块打打断调试看看，我目前没有想到或者碰到过`yog-view`输出了，但是没有进入页面的case。
