### ISSUE TITLE
如果让yog2支持coffee编译？

### ISSUE THREAD

**Issue by lys623** [fex-team/yog2#6]

**Comment by hefangshi** [comment]
支持coffee编译的方式和FIS没有区别，不过server目录下的代码默认不进行编译，所以需要做一些调整。

**Comment by lys623** [comment]
fis release 的时候可以正确编译成js文件，yog2 release的时候，文件时转成了js，但内容还是coffee的，哪里配置错了？

**Comment by hefangshi** [comment]
你应该是说的server下的文件吧，server下的配置需要做我上面说的处理，client下的只要fis release可以正常编译，在Yog2下也可以正常编译

**Comment by lys623** [comment]
好了
