### ISSUE TITLE
yog-swig可不可以取消对swigInstance 的缓存呢？

### ISSUE THREAD

**Issue by dodio** [fex-team/yog2#62]
话说，我看到yog-swig里对swig的实例有缓存。
    // if (swigInstance) {
    //     debuglog('use swig instance cache');
    //     this.swig = swigInstance;
    //     return;
    // }
以及 plugins/view.js 里使用了 viewEngine.renderFile.bind(viewEngine)
这样会妨碍一个进程中存在多个 里存在多个 并行的环境。
不知道这样设计的考虑是什么？
是不是 就不建议一个node进程内跑多个实例？

其实，我自己做的东西，主要是增加了 虚拟主机的功能，在不使用反向代理的情况下，
www.example.com
m.example.com
admin.example.com 都是可以被访问.当然也能共享一部分代码。

**Comment by hefangshi** [comment]
复用swig实例有什么问题么？希望完全独立的运行环境的话就不应该在一个node进程内执行，毕竟一个请求crash会导致整个node程序crash。

**Comment by dodio** [comment]
是的。容易导致整个应用crash 的问题。

**Comment by dodio** [comment]
不同应用会有不同的 views 模板目录嘛，复用了以后，所有的应用内的模板 在 include 或者 extend的时候，使用的就都是 第一次生成实例时的目录了。

**Comment by hefangshi** [comment]
你就不能设计成不同应用使用不同的目录，但是都是在views模板目录下么？类似yog2这样。另外还是上面说的，不建议把太本应独立的业务，放在一个服务内。

**Comment by dodio** [comment]
嗯。明白你的意思。其实我说的情况，主要还是是应该做成 独立的服务。

**Comment by dodio** [comment]
我说的情况主要还是，想在两个 域名下能 共享一些东西， 比如： www.example.com  与 admin.example.com 中间共用一下。 因为我这是小项目嘛， 不像你们 可能管理平台会做为一个独立的大项目的来做。

**Comment by hefangshi** [comment]
![image](https://cloud.githubusercontent.com/assets/613846/11324626/01b39a5c-9172-11e5-942c-89aa31619a41.png)

这就是yog2的app的概念啊

**Comment by dodio** [comment]
嗯啊。了解了。
