### ISSUE TITLE
 file.getMtime(...).getTime is not a function

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2#63]
使用yog2 release --dest dev --watch进行监听文件，无规律出现错误：
 file.getMtime(...).getTime is not a function

**Comment by hefangshi** [comment]
未复现过，可以给一下更全的错误信息么？直接截图。

**Comment by rendongsc** [comment]
![yog2](https://cloud.githubusercontent.com/assets/12553638/11461249/7299a7d4-973a-11e5-8580-8b0583c7fa5f.png)

**Comment by hefangshi** [comment]
你有自己使用一些插件么

**Comment by rendongsc** [comment]
插件列表：redis、knex和session。
好像是更新了"yog2-kernel": "0.4.0"后才偶尔出现这个问题。

**Comment by hefangshi** [comment]
这个错误和运行时的插件无关，只和yog2-cli的插件有关，也就是说fis的插件

**Comment by rendongsc** [comment]
没有用到其他fis插件

**Comment by hefangshi** [comment]
先升级最新版的yog2看看，我们这边使用中从没碰到过这种情况。你重现是需要一些操作还是某些模块频繁出现？

**Comment by rendongsc** [comment]
系统是window10，出现此问题是无规律的。
