### ISSUE TITLE
接收信号动态调整日志等级

### ISSUE THREAD

**Issue by hefangshi** [fex-team/yog2#65]
方便在线上通过发送信号获取更详细的日志

**Comment by v-joy** [comment]
个人感觉 此需求不强烈 

好处:
对于线上出了问题，并且必须在线上复现时，能够接收信号调整等级有一定好处:

非好处:
1. 日志等级的调整不频繁；一般设定好了日志等级后极少变化;
2. 存在状态要不要持久化的问题，比如初始状态是4 接受信号调整到16了  重启之后应该是4呢  还是16呢？
3. 增加代码复杂度
4. 这个信号是指http信号呢，还是kill的信号呢？   如果kill的信号，感觉和reload没什么大区别, 如果是http信号，如何避免外网的访问等问题也需要解决

**Comment by hefangshi** [comment]
kill信号，reload实际上进程还是会重启的，而实际上有时候进程重启后异常就无法复现了。

另：这个功能极其简单

**Comment by superlbr** [comment]
话说我日志打出来的时间是GMT。。。能改下时区不
![image](https://cloud.githubusercontent.com/assets/8142164/14705388/cf8e463a-07eb-11e6-9538-06b201190ad2.png)
