### ISSUE TITLE
如何配置多个静态文件目录？或者如何把某个app的的目录也设为静态文件目录？

### ISSUE THREAD

**Issue by lys623** [fex-team/yog2#7]

**Comment by hefangshi** [comment]
不建议做这样的操作，毫无意义，而且不便于管理，比如CDN回源接入的时候，你会需要设置多个回源路径。此外还会造成网站目录结构混乱，特别是在每个APP目录都设置一个静态文件目录。

YOG2下的静态资源目录的文件结构是 `/static/APP_NAME/`，实际上已经按照APP做了区分了。

如果坚持有这样的需求也很方便实现，按照YOG2的插件规范在用户代码中重写一个 [static](https://github.com/fex-team/yog2-kernel/blob/master/plugins/http/middleware/static.js) 插件就可以了。

**Comment by lys623** [comment]
好的，谢了
