### ISSUE TITLE
bigpipe.bind 绑定的id可以是在tpl中显示声明一个文件片段，而不必把这个片段当作文件引进来吗？

### ISSUE THREAD

**Issue by Arnoldnuo** [fex-team/yog2#71]
现在bigpipe.bind的写法只能是引入一个文件，这样使用bigpipe.bind多了以后，导致文件会很多，有没有 {%widget%} content{%endwidget%} 类似这样的写法？不用单独拆分一个文件？

**Comment by dodio** [comment]
这确实是个好主意

**Comment by 2betop** [comment]
+1

**Comment by hefangshi** [comment]
考虑了一下，会作为1.0的milestone引入

**Comment by hefangshi** [comment]
落地 https://github.com/fex-team/yog2-kernel/releases/tag/1.1.0
