### ISSUE TITLE
能否完善最近更新的文档说明！

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2#74]
yog2支持es6和typescript了，非常好！
相应文档没有更新，有两点疑惑？
1、前端require:es文件时，文件名是写*.es还是编译后的*.js文件名？
2、同上，如果是服务端引用呢？
yog2目前还是只有一个spa项目案例，可否增加yog2重要特性的代码段和fis相关配置吗？
谢谢！

**Comment by hefangshi** [comment]
仍在施工中，目前yog2正朝向 1.0 milestone 进发中，不建议使用没有文档的功能

以下是近期会优先补充的文档

1. ral的degrade与mock功能
2. yog2服务端代码使用 async/await 语法的demo [施工中](https://github.com/hefangshi/yog2-newtype-demo)
3. yog2客户端代码使用 es6, react 技术的demo
4. BigPipe、Quickling、Sync三种模式自适应切换的文档
