### ISSUE TITLE
完全按照readme步骤，但是调试模式没有启动！请问怎么解决？

### ISSUE THREAD

**Issue by guzhou-git** [fex-team/yog2#76]
![2015-12-28_114405](https://cloud.githubusercontent.com/assets/12030867/12013728/db855936-ad57-11e5-88fb-7e65c49a73f7.png)

**Comment by hefangshi** [comment]
看起来已经启动了，不过看起来你并没有把 home 模块发布到运行环境中。再看一次文档？

**Comment by guzhou-git** [comment]
新建的APP必须起名home我也是醉了。
如果要改端口配置也要改好几个地方才行！要不然APP还发布不过来。

**Comment by hefangshi** [comment]
并没有要求新建的 APP 起名 home，只是不叫 home 的话，是需要在访问 url 上带上 app 名称的，具体细节可以去看文档的路由章节。

改端口需要调整 server 和 app 中的 fis-conf.js。需要两个配置能够对应上才有效。这个应该不难理解吧？否则 app 与发布的 project 目标就会变成紧耦合的了，当你多个开发环境的端口配置不一样的时候，你如何部署？

很多设计细节最好多看看文档，多使用一下思考一下在下结论。
