### ISSUE TITLE
yog2重启问题

### ISSUE THREAD

**Issue by DeyuanTan** [fex-team/yog2#80]
YOG_DEBUG 设置为 false 之后，recv-reload 这个插件就用不了了。
那 Release 之后怎么去重启 yog2 app？
要使用  pm2之类工具？

**Comment by hefangshi** [comment]
是的，线上服务部署建议使用PM2一类的工具去重启服务。

**Comment by superlbr** [comment]
pm2开着的时候，无法release呀
