### ISSUE TITLE
yog2 0.5.0 版本运行 yog2 release -cmlupwd debug 命令报错

### ISSUE THREAD

**Issue by HellowVirgil** [fex-team/yog2#82]
##0.5.0版本运行 yog2 release -cmlupwd debug 报unreleasing错误
* 发现是运行到fis-conf.js中pack选项报错
* 去除-p选项使用 yog2 release -cmluwd debug 可正常运行

##0.3.1版本正常

**Comment by hefangshi** [comment]
升级至0.5.2可以解决这个问题

**Comment by HellowVirgil** [comment]
@hefangshi thx~
