### ISSUE TITLE
mac 下无法加载静态资源？

### ISSUE THREAD

**Issue by rendongsc** [fex-team/yog2#83]
在windows 10环境是OK的，切换到mac系统，mac环境下的文件及文件夹与Windows是一致的，通过yog2 run运行，但是无法加载静态资源文件。
估计是什么原因？
![image](https://cloud.githubusercontent.com/assets/12553638/13769840/b0d05b8e-eabd-11e5-90b4-6c9127762131.png)

**Comment by rendongsc** [comment]
是部署app时造成的，之前的fis.config配置有问题。

**Comment by rendongsc** [comment]
yog2升级到最新版，用命令行发布：
yog2 release --dest debug --watch
有问题，导致app-map.json不完整，故产生了上面的错误！
是fi3的问题？

**Comment by hefangshi** [comment]
```
yog2 release --dest debug --watch
```

默认执行的是 fis2 核心。命令问题可以先参考一下#84
