### ISSUE TITLE
token应该保存在yog2还是浏览器

### ISSUE THREAD

**Issue by xxapp** [fex-team/yog2#88]
项目里用yog2调用jwt作认证的后端服务
如果把token存在yog2，浏览器端和yog2需要保持一个会话状态。
如果把token存在浏览器，一些做后端渲染的action里面又不好把token放到url里面。
所以感觉这里有点迷惑，请 @hefangshi 指点

**Comment by hefangshi** [comment]
可以学习一下jwt的做法。一般来说，是推荐保存在本地的，比如放在localStorage中(可以使用cookie作为降级)，至于如何传入，可以在认证成功后，返回浏览器端，并不是每次渲染都需要带上的

**Comment by xxapp** [comment]
好的，谢谢。
还有一个问题，token保存在客户端本地，如果我有一个后端渲染的请求，像这样
```
index?pagelets[]=spage
```
而且这个后端渲染的过程包含后端服务的调用
请求也不是我主动用js发起的

这种情况下，我怎么把token传给yog2并且调用服务的时候带上这个token?

**Comment by xxapp** [comment]
我想到一个办法，可以在浏览器端override bigpipe 的Util.ajax，带上自己的header
``` js
BigPipeUtil.ajax = function (url, cb, data) {
        var xhr = new(window.XMLHttpRequest || ActiveXObject)('Microsoft.XMLHTTP');

        xhr.onreadystatechange = function () {
            if (this.readyState == 4) {
                cb(this.responseText);
            }
        };
        xhr.open(data ? 'POST' : 'GET', url + '&t=' + (new Date()).getTime(), true);

        if (data) {
            xhr.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
        }
        xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
        // 自己的header
        xhr.setRequestHeader('Authorization', tokenFromStorage);
        xhr.send(data);
}

```
不过有一个问题是每次都要在yog2里面手动取header，再用yog.ral把header传给后端服务。

**Comment by hefangshi** [comment]
token不一定要写在头部中，你可以在URL处添加jwt参数。在Quickling模式下，BigPipe.load 的API是允许自定义参数的。

yog2 通过 RAL 与后端交互的问题，可以考虑自行封装一个接口来处理每次的header透传以及logid的传递等工作。

**Comment by xxapp** [comment]
我明白了，非常感谢！
