### ISSUE TITLE
业务逻辑的书写

### ISSUE THREAD

**Issue by AceLing** [fex-team/yog2#89]
yog2的业务逻辑必须写在router.js吗

action的作用是什么？

**Comment by hefangshi** [comment]
业务逻辑一般是写在/server/model中，action用于处理各个请求，分解参数，请求Model层，渲染页面。可能包含部分业务逻辑。

router只是用来做请求转发的，比如实现一些需要特殊定制的URL和Restful API的参数一类需要。

**Comment by AceLing** [comment]
如果业务逻辑写在model层，即是业务逻辑与做数据持久化的逻辑放在一起？
还是除了model层以外还有别的层级？
还有想请教一下yog2是属于RESTful吗？

**Comment by hefangshi** [comment]
model层可以继续细分出业务逻辑层和数据层，yog2并没有在这一部分提供很多硬性规定，可以由用户自行组织。

YOG2是否属于Restfull是看业务代码如何编写，本身没有限制这方面的功能，也没有针对Restfull做很特别的优化。
