### ISSUE TITLE
用Fis 的 postprocessor插件，只是能在Client里面部署，而不能放在View里面噢？

### ISSUE THREAD

**Issue by jincdream** [fex-team/yog2#9]

**Comment by hefangshi** [comment]
可以处理 `View` 的数据，并没有限制，不过需要自行添加配置，因为 yog2 默认是 `server` 目录中不做任何处理。

**Comment by jincdream** [comment]
那Sever 里面的 client 要怎么访问到？action 也好像无法指向到client文件夹

**Comment by hefangshi** [comment]
你希望在 Server 里面访问到 Client的话，并没有直接的办法，实际上 yog2 还是遵循的前后端代码分离开发的模式，目前并没有在前后端逻辑复用上形成很成熟的方案，主要是因为这其中一旦涉及到安全问题就很难解决。

但是目前可以在可控的范围内容做到一定的代码复用。方案其实很简单，你如果希望server与client中有代码是复用的，可以在一处编写代码，另一处建立一个空文件，里面使用FIS的资源内嵌功能 `__inline('/client/widget/util/error.js')` 来实现一份代码多处使用的功能。

**Comment by jincdream** [comment]
恩。安全是一个问题，不过我现在是想这样:
```javascript
fis.config.set('roadmap',{
  path:[{
    reg: '**.html',
    useMap: !0,
    charset:'gbk'
  },
  {
    reg: '**.tpl',
    useMap: !0,
    charset:'gbk'
  }]
})
```
发现不能对views里面的进行匹配。
然后看到yog2的配置已经这样了:
```
{
    reg: /^\/client\/(.*)/i,
    id: '$1',
    release: '${static}/${namespace}/$1'
}
```

是不是相当于已经被写死了。

**Comment by hefangshi** [comment]
并没有写死，你可以使用 unshift 添加自己的规则，具体可以查看文档

http://fis.baidu.com/docs/advance/roadmap.html

**Comment by jincdream** [comment]
恩。我刚也想到了。不过这还是应该在yog2里面说明下嘛~

**Comment by hefangshi** [comment]
fis的文档实在太多，并不能全部搬过来，不过最近正在整理文档，稍晚会加进来这部分，因为很重要。

**Comment by jincdream** [comment]
恩。确实。好的Thx~

**Comment by jincdream** [comment]
还有个问题  http://127.0.0.1/favicon.ico  这个路由要怎么定义。

**Comment by hefangshi** [comment]
https://github.com/fex-team/yog2-framework-template/blob/master/conf/plugins/http.js#L86-L97

不过如果希望建立md5的话，还是最好在页面中指定favicon

在 2015年6月5日 下午8:10，Jin_C <notifications@github.com>写道：

> 还有个问题 http://127.0.0.1/favicon.ico 这个路由要怎么定义。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fex-team/yog2/issues/9#issuecomment-109271479>.
>



-- 
Your Truly,
He

**Comment by jincdream** [comment]
https://github.com/fex-team/yog2-framework-template/blob/master/conf/plugins/http.js#L86-L97
module.exports.static 这个要怎么进行多个目录的static设置呢？例如我想针对每个app的static文件夹进行设置。

**Comment by jincdream** [comment]
好像默认就有。不过，```static/sale/static/``` ,,, 不过感觉路径太长了。

**Comment by hefangshi** [comment]
可以直接写在layout.tpl的favicon中，当成图片一样对待，这样还可以处理MD5戳

觉得路径长的话可以不放在static目录下
